### ISSUE TITLE
[FEATURE] Adding Supabase social auth providers

### ISSUE THREAD

**Issue by MvE10** [SiddhantSadangi/st_login_form#13]
Currently the solutions works perfect for Supabase email login! Would it also be possible to add other Supabase integrated providers as well? This could be similar to the [streamlit-supabase-auth package](https://github.com/sweatybridge/streamlit-supabase-auth)

**Describe the solution you'd like**
The option to also add the social auth providers as option for login, but keeping the same dynamic under the hood with Supabase as central orchestrator.

**Describe alternatives you've considered**
Obviously the  [streamlit-supabase-auth package](https://github.com/sweatybridge/streamlit-supabase-auth), but the design is not really nice, cannot be changed and is less Streamlit first than st_login_form.

**Comment by SiddhantSadangi** [comment]
Hey @MvE10 👋 
I thought of adding more Supabase-supported auth providers, but I want to make this component database agnostic, and adding more Supabase-specific features would be a step in the opposite direction 😔 

Could you use https://github.com/SiddhantSadangi/st_supabase_connection instead? It supports all Supabase features, including Auth. You will, however, need to build a front-end yourself.

Let me know what you think.

Depending on what the community wants, I might also give up making it DB agnostic and concentrate on supporting more Supabase features (or maybe try and do both). So this feature request is definitely not off the table yet :)
