### ISSUE TITLE
:warning: careful when writing secrets.toml

### ISSUE THREAD

**Issue by spacewaterbear** [SiddhantSadangi/st_login_form#2]
### Problem
According to  [this streamlit documentation](https://docs.streamlit.io/knowledge-base/tutorials/databases/supabase#sign-in-to-supabase-and-create-a-project), you need to write this in your secrets.toml : 
```
# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "xxxx"
SUPABASE_KEY = "xxxx"
```
But if you do that, you will have this error : 

KeyError: 'st.secrets has no key "SUPABASE_URL".

### Solution
1. either propose to the user to fill secrets.toml file following this pattern
```
# .streamlit/secrets.toml
SUPABASE_URL = "xxxx"
SUPABASE_KEY = "xxxx"
```

2. edit the code so it can access the SUPABASE_URL and SUPABASE_KEY with the nested dictionnary st.secrets["connections"]["supabase"]["SUPABASE_URL"]

I can make a pull request for the second option if you want

**Comment by SiddhantSadangi** [comment]
Hey @spacewaterbear 👋 

Thanks a ton for bringing this to my notice 🙇 
I've just released [v0.2.2](https://github.com/SiddhantSadangi/st_login_form/releases/tag/0.2.2) with the changes 🚀 

To preserve backward compatibility, you can still pass the secrets outside of a table in the `.secrets.toml` file, although secrets passed in the `[connections.supabase]` table will take precedence.

Please let me know if this works for you.
